### ISSUE TITLE
Lutris installer takes around 30 min before starting the download

### ISSUE THREAD

**Issue by CPUFronz** [GloriousEggroll/warframe-linux#20]
When I first installed Warframe via Lutris, I thought the installer was broken, because it showed no progress and also my computer didn't show much activity. The script did finish (I'm not sure, but I guess it took 30 minutes), after some investigation I figured out, that the following 6 bash instructions are causing problems:

```yaml
- execute:
    args: -c "mv $GAMEDIR/drive_c/Program\ Files/Warframe/warframe-linux-master/*
      $GAMEDIR/drive_c/Program\ Files/Warframe/"
    file: /bin/sh
- execute:
    args: -c "rm -R $GAMEDIR/drive_c/Program\ Files/Warframe/warframe-linux-master/"
    file: /bin/sh
- execute:
    args: -c "chmod a+x '$GAMEDIR/drive_c/Program Files/Warframe/wget.exe'"
    file: /bin/sh
- execute:
    args: -c "mkdir -p '$GAMEDIR/drive_c/users/$USER/Local Settings/Application Data/Warframe'"
    file: /bin/sh
- execute:
    args: -c "sed -i \"s/%USERNAME%/\"$USER\"/g\" $GAMEDIR/drive_c/Program\ Files/Warframe/wf.reg"
    file: /bin/sh
- execute:
    args: -c "mv '$GAMEDIR/drive_c/Program Files/Warframe/EE.cfg' '$GAMEDIR/drive_c/users/$USER/Local
      Settings/Application Data/Warframe/EE.cfg'"
    file: /bin/sh
```

It seems like bash doesn't finish after those instructions are executed: e.g. the files are moved from `$GAMEDIR/drive_c/Program\ Files/Warframe/warframe-linux-master/*` to `$GAMEDIR/drive_c/Program\ Files/Warframe/"`, but then nothing happens for some minutes until the next bash instruction is executed with the same problem afterwards. 

Once they are done, the script is installing the additional libraries as fast as you'd expect. Is it a know problem from Lutris (I'm using the latest version 0.4.14 on Ubuntu 17.10)?
